# Manila
manila_protocols:
  - NFS
  - CIFS
  - CEPHFS

# manila_backend_rbd_inuse: True

manila_backends:
  cephfsnfs1:
    ganesha_rados_store_enable: True
    ganesha_rados_store_pool_name: cephfs_data
    driver_handles_share_servers: False
    service_instance_user: manila
    service_instance_password: "{{ manila_service_password }}"
    share_backend_name: CEPHFSNFS1
    share_driver: manila.share.drivers.cephfs.driver.CephFSDriver
    cephfs_protocol_helper_type: NFS
    cephfs_conf_path: /etc/ceph/ceph.conf
    cephfs_auth_id: manila
    cephfs_cluster_name: ceph
    cephfs_enable_snapshots: False
    cephfs_ganesha_server_is_remote: True
    cephfs_ganesha_server_ip: 
    cephfs_ganesha_server_username: root
    cephfs_ganesha_path_to_private_key: /etc/manila/id_rsa

manila_default_store: cephfsnfs1
